### ISSUE TITLE
Allow non-native s3 provider

### ISSUE THREAD

**Issue by qmnonic** [transferwise/pipelinewise-tap-s3-csv#3]
Currently this tap only works for AWS S3.  Please update to work with non-AWS S3 providers (example: digitalocean spaces).

**Comment by koszti** [comment]
PR merged https://github.com/transferwise/pipelinewise-tap-s3-csv/pull/4
and it's now part of the main PipelineWise. Updated documentation is at https://transferwise.github.io/pipelinewise/connectors/taps/s3_csv.html

Thanks for the contribution
